services:
  db:
    container_name: place-service-db
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: portalgen_place
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306'
